### ISSUE TITLE
Firefox - Enter key makes <br> instead of <p>

### ISSUE THREAD

**Issue by limonte** [textAngular/textAngular#1112]
![recorded](https://cloud.githubusercontent.com/assets/6059356/13898709/8833b200-edda-11e5-9f59-9a01f3b76174.gif)

As you can see from this gif, actual result is `<p>11<br/>22<br/><br/></p>`

Expected result (Chrome works fine): `<p>11</p><p>22</p><p><br/></p>`

**Comment by AzRu** [comment]
I'm seeing a similar issue where a </br> is inserted at the end of the message when using firefox, but fine when I use chrome. textAngular 1.5.1
