### ISSUE TITLE
wrapSelection does not update my model

### ISSUE THREAD

**Issue by sebius8780** [textAngular/textAngular#1303]
Hello there, thank you for the great great work !

I have an issue, maybe it is something I have done wrong, I checked all wiki / pages and don't find any answer.
I pick some extra code to add the ability to highlight some text, but when I check the value stored via the ng-model directive some of it is missing :

The extra code : 

FormApp.config(function($provide)
{
// this demonstrates how to register a new tool and add it to the default toolbar
$provide.decorator('taOptions', ['taRegisterTool', '$delegate', function(taRegisterTool, taOptions) 
{
 // $delegate is the taOptions we are decorating
 taRegisterTool('markYellow', {
 tooltiptext : "surligner en jaune",
 iconclass : "fa fa-square yellow",
 action : function() { this.$editor().wrapSelection('backcolor', 'yellow'); }
 });
 taOptions.toolbar[2].push('markYellow');
 taRegisterTool('colourRed', {
   tooltiptext : "marquer comme important",
   iconclass : "fa fa-square red",
   action : function() {
           this.$editor().wrapSelection('backcolor', 'red');
          this.$editor().wrapSelection('forecolor', 'white');
          this.$editor().wrapSelection("bold", null);
     }
   });
   // add the button to the default toolbar definition
   taOptions.toolbar[2].push('colourRed');
   return taOptions;
 }]);
});

so the result that appears is the right one : 
![image](https://cloud.githubusercontent.com/assets/2934173/18281644/42935b40-7423-11e6-9146-2aa19545c2d8.png)

But in the model variable I have this : 
`<p>test qui est pas si <span><span><font color="#ffffff"><b>mauvais</b></font></span></span></p>`

Lacking the style attribute for background color on the first <span>.
I use angular 1.5.8 / last version (06/09/2016) of textAngular ( with rangy )

**Comment by portus84** [comment]
+1

**Comment by sebius8780** [comment]
Hello ! 
Is there something we can do about this please ?
What I think is happening here is that calling 
this.$editor().wrapSelection('backcolor', 'red');
this.$editor().wrapSelection('forecolor', 'white');

makes the background-color style disappear somehow within the ng-model value ?
Could you please check it out ?

Thanks !!

**Comment by ericWenjp** [comment]
i hava the same problem at v1.5.16 ,but v1.4.6 works

**Comment by galiling** [comment]
I spent a few hours on this and I found that in v1.5.16 setting "taKeepStyles" to true will fix this.
