### ISSUE TITLE
Not able to load 'textAngular' using Webpack

### ISSUE THREAD

**Issue by kalpitpandit** [textAngular/textAngular#1323]
Getting **Module not found: Error: Cannot resolve module 'textAngular'** using webpack. 

```
export default require('angular')
    .module('xyz', [
        require('angular-sanitize'),
        require('textAngular'),
    ]);
```

I am using **1.5.9** version.

**Comment by JoelParke** [comment]
Have your taken a look at #1015 - which connects to this issue.  I am in the middle of some other fixes and want to get to this and others, but it will be a couple of weeks.  Please let me know what you find! thanks!
