### ISSUE TITLE
Documentation: How to focus text-angular programatically

### ISSUE THREAD

**Issue by mreiche** [textAngular/textAngular#687]
I tried to use a directive which sets the focus for an element, but this won't work with text-angular.
Is there a feature, to focus a text element programatically (ea. for use in ui-router).

**Comment by SimeonC** [comment]
We don't have a feature but this should theoretically be possible - I think contenteditables can be focussed that way.

AFAIK it should be as simple as calling `.focus()` on the element, but you may need to put this in a timeout to make sure it's all loaded up properly, if not it won't have the correct div to focus available yet (It's a child node of the text-angular element).

**Comment by diego-vieira** [comment]
Was looking for the same and this is how I resolved.

```html
<text-angular name="some-id" ng-model="message"></text-angular>
```

```javascript
$timeout(function() {
    angular.element('text-angular[name=some-id]').find('*[id*=taText]').focus();
});
```
